### ISSUE TITLE
Error when get cards

### ISSUE THREAD

**Issue by odysseus1973** [gregsdennis/Manatee.Trello#148]
Hello!

When I try to get cards, a receive error "Requested value 'light' was not found."

```
   at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ProcessRequest[T](IRestRequest request, Object obj)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.Execute[T](TrelloAuthorization auth, Endpoint endpoint, IDictionary`2 parameters)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge()
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext.Synchronize(Boolean force)
   at Manatee.Trello.Board.get_Id()
   at Manatee.Trello.ReadOnlyCollection`1.get_OwnerId()
   at Manatee.Trello.ReadOnlyCardCollection.Update()
   at Manatee.Trello.ReadOnlyCollection`1.GetEnumerator()
   at AsnaWebAddIn.AsnaRibbon.trelloBtn_Click(Object sender, RibbonControlEventArgs e) in C:\Git\AsnaWebAddIn\AsnaWebAddIn\AsnaRibbon.cs:line 36
```

At line 36 

```
 var board = new Board("myboardid");
-->    foreach (var card in board.Cards)
```

In response I can see this property 

```
Name	        Type	Value
backgroundBrightness	object	"light"
```

P.S. When I change board background to green, the error disappeared 

Thanks

**Comment by gregsdennis** [comment]
Awesome! You found a new value! I'll add it and post an update.  Thanks.
