### ISSUE TITLE
Manatee.Trello tries to write a file on exit (licensing)

### ISSUE THREAD

**Issue by agross** [gregsdennis/Manatee.Trello#202]
I use Manatee.Trello in a services hosted with minimum permissions (Network Service). When the service exists, Manatee.Trello tries to write a file in a directory where the service has no permission to write (`C:\Windows\system32`, the default working directories of Windows Services).

Seems to be related to licensing:

```
System.UnauthorizedAccessException: Access to the path 'C:\windows\system32\Manatee.Trello.run' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Manatee.Trello.Internal.Licensing.LicenseHelpers.SaveCurrentState()
   at Manatee.Trello.TrelloProcessor.<Flush>d__0.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\windows\system32\Manatee.Trello.run' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Manatee.Trello.Internal.Licensing.LicenseHelpers.SaveCurrentState()
   at Manatee.Trello.TrelloProcessor.<Flush>d__0.MoveNext()<---
```

**Comment by gregsdennis** [comment]
This is a mechanism I use to track usage between individual runs.  I know I need to put it somewhere else.  I hadn't considered not being able to write to the program directory.

**Comment by TimSirmovics** [comment]
We use the API via an app hosted on IIS and the file needs to be written to `c:\windows\system32\inetsrv\Manatee.Trello.run`. Luckily we have control over the web server and could give permission to write the file their, but it would be better to write to another location.

**Comment by gregsdennis** [comment]
I've updated this to write to the local app data folder for the current user.  That should fix the problem.

I initially avoided that because I was lazy and didn't want to specify different folders per OS, but it seems that's the best way, so...

Anyway, I'll have this merged into the **release-3.0.8** branch soon.

**Comment by gregsdennis** [comment]
It looks like appveyor doesn't like me writing to that folder.  It's failing the tests.  It'll likely fail when writing to any folder other than the build folder.  I'd hate to have this as some sort of configuration.... that feels wrong.

Unless either of you have an idea, the only other option I can conceive is to disable the persistence.

**Comment by gregsdennis** [comment]
I think I resolved the different OSes bit in that I detect the OS and provide the appropriate user directory accordingly.  I think persisting it to a file is wrong.  I'm new to this bit, though, so it's going to take some experimentation.

**Comment by TimSirmovics** [comment]
What about `Path.GetTempPath()`? I think this is supposed to return a temporary path on both Unix and Windows so should presumably work for any environment. [here](https://github.com/dotnet/corefx/issues/13710) is a thread with some arguments about where exactly the temp path should resolve to on Unix.

**Comment by gregsdennis** [comment]
I've settled putting this in a user-level environment variable.  Sadly, writing to user-level vars isn't available to Standard 1.x, but it's the best option so far.  I've also wrapped it in a try/catch that merely logs any errors.
