### ISSUE TITLE
Cannot set number field with decimal places

### ISSUE THREAD

**Issue by agross** [gregsdennis/Manatee.Trello#203]
Whenever I try to set a custom field of type `number` to a `double` that contains decimal places, the following is logged:

```
Sending: Put card/5af5d4ef7183551238934567/customField/5af5c9b56ba18a8214c12126/item
Status Code: BadRequest (400)
Content: Invalid custom field item value.
Received: Invalid custom field item value.
```

```cs
// Works.
field.SetValueForCard(card, 123);

// Does not work.
field.SetValueForCard(card, 123.45);
```

**Comment by agross** [comment]
Now I get this logged:

```
Sending: Put card/5af6a0946e7d4ab44267e07f/customField/5af5c9bc265ba0e80cd7a732/item
Status Code: BadRequest (400)
Content: Invalid custom field item value.
Received: Invalid custom field item value.
Trello Error
Manatee.Trello.TrelloInteractionException: Trello has reported an error with the request: Invalid custom field item value.
2018-05-12 10:06:51,363 [       23] ERROR s.Features.Trello.Handler - Could not save field Number with data 123.45: Manatee.Trello.TrelloInteractionException: Trello has reported an error with the request: Invalid custom field item value.
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestResponse response)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<ProcessRequest>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<Execute>d__3`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manatee.Trello.Internal.Synchronization.CustomFieldDefinitionContext.<SetValueOnCard>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manatee.Trello.CustomFieldDefinition.<SetValueForCard>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ops.Features.Trello.Handler.<MapField>d__6.MoveNext() in ops\source\Ops\Features\Trello\Handler.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Ops.Features.Trello.Handler.<MapFields>d__5.MoveNext() in ops\source\Ops\Features\Trello\Handler.cs:line 93
```

**Comment by agross** [comment]
Does it work for you if you put a double with decimal places [here](https://github.com/gregsdennis/Manatee.Trello/blob/master/Manatee.Trello.IntegrationTests/CardTests.cs#L93)?

**Comment by gregsdennis** [comment]
Yes. I changed that value from 9 to 9.6, and the test passes. I can set the value and retrieve it.

**Comment by agross** [comment]
Yep, it does relate to the current culture: If I change my Windows number display format to English the `double` is serialized as `123.45` and the request succeeds. In German locale, this number would be represented as `123,45`. I sense a missing `CultureInfo.InvariantCulture` where to conversion is made.

**Comment by gregsdennis** [comment]
I'm pretty sure I set this in my JSON lib. I remember having this issue before. I'll check.

**Comment by gregsdennis** [comment]
Yep, the culture is apparently the issue....

Ah!  Trello specifies that custom field values must always be set as strings!  So the serializer is never serializing a number, the conversion is in the Trello lib.  There are so many of these stupid little variances in their API!

**Comment by gregsdennis** [comment]
Okay.  Please give v3.0.9 a go.

**Comment by agross** [comment]
3.0.9 works. Many thanks!
