### ISSUE TITLE
Exception when copying card

### ISSUE THREAD

**Issue by agross** [gregsdennis/Manatee.Trello#205]
Just got this on my production system after doing the upgrade today:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Manatee.Trello.Internal.Caching.ConcurrentCache.Find[T](String id)
   at Manatee.Trello.Internal.Caching.CachingObjectFactory.GetFromCache[T](IJsonCacheable json, TrelloAuthorization auth)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Manatee.Trello.ReadOnlyCollection`1.Update(IEnumerable`1 items)
   at Manatee.Trello.Internal.Synchronization.AttachmentContext.MergeDependencies(IJsonAttachment json)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge(TJson json, Boolean overwrite)
   at Manatee.Trello.Internal.Synchronization.CardContext.<MergeDependencies>b__47_1(IJsonAttachment a)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Manatee.Trello.ReadOnlyCollection`1.Update(IEnumerable`1 items)
   at Manatee.Trello.Internal.Synchronization.CardContext.MergeDependencies(IJsonCard json)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge(TJson json, Boolean overwrite)
   at Manatee.Trello.CardCollection.<CreateCard>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.CardCollection.<Add>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ops.Features.Trello.Handler.<Handle>d__4.MoveNext() in C:\BuildAgent\work\d8126f682f27008b\source\Ops\Features\Trello\Handler.cs:line 46
```

Handler.cs:line 46 contains:
```cs
var board = _trello.Board("some board ID");
await board.Lists.Refresh();
var list = board.Lists["some list ID"];
var cards = list.Cards;
card = await cards.Add(_trello.Card("some template card ID")); // line 46
```

The error is persistent, i.e. doesn't go away when the request is repeated by the system. On Trello web I can see the template card being copied, but no modifications were made to them. (Modifications happen after line 46.)

**Comment by gregsdennis** [comment]
@agross I'm going to go ahead and push out v3.0.8.  We can review this if you're still having trouble with it.

**Comment by agross** [comment]
Right before the error is thrown (and after the card has been copied from the template card) this is logged:

```
Sending: Post cards
Status Code: OK (200)
Content: {"id":"5af6e0740be4f8e8fb55f782","badges":{"votes":0,"attachmentsByType":{"trello":{"board":0,"card":0}},"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":21,"checkItemsChecked":0,"comments":0,"attachments":1,"description":true,"due":null,"dueComplete":false},"attachments":[{"id":"5af6e0740be4f8e8fb55f783","bytes":9782,"date":"2017-04-17T11:00:27.936Z","edgeColor":"#fbfbfb","idMember":"5af6e0740be4f8e8fb55f784","isUpload":true,"mimeType":null,"name":"am 17.4.2017 um 13:00:29 hochladen.png","previews":[{"bytes":1512,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/70x50/b517781044d2e4a2cea9e665ddd4a013/am_17.4.2017_um_13_00_29_hochladen.png","height":50,"width":70,"_id":"5af6e0740be4f8e8fb55f785","scaled":false},{"bytes":11454,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/250x150/9a4b3e2477e69a64541fd20db82ce567/am_17.4.2017_um_13_00_29_hochladen.png","height":150,"width":250,"_id":"5af6e0740be4f8e8fb55f786","scaled":false},{"bytes":5164,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/150x18/c2f87a31cc4f516e23d877ca13a180bc/am_17.4.2017_um_13_00_29_hochladen.png","height":18,"width":150,"_id":"5af6e0740be4f8e8fb55f787","scaled":true},{"bytes":14339,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/300x37/7f725ab87b73992151475e1ec9030010/am_17.4.2017_um_13_00_29_hochladen.png","height":37,"width":300,"_id":"5af6e0740be4f8e8fb55f788","scaled":true},{"bytes":9782,"height":41,"width":335,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/335x41/931fb24b7bb10ee1fab78f577b29adc4/am_17.4.2017_um_13_00_29_hochladen.png","_id":"5af6e0740be4f8e8fb55f789","scaled":true}],"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/x/2fab975fd20ddd390557db42fcf032d4/am_17.4.2017_um_13_00_29_hochladen.png","pos":16384}],"checkItemStates":[],"closed":false,"dueComplete":false,"dateLastActivity":"2018-05-12T12:39:16.903Z","desc":"The description.","descData":{"emoji":{}},"due":null,"email":null,"idBoard":"4f2ef2f82e7ecf843fb79649","idChecklists":["5af6e0740be4f8e8fb55f78d","5af6e0740be4f8e8fb55f7a0"],"stickers":[],"idList":"52ce972a1c855c5a309edd82","idMembers":[],"idMembersVoted":[],"idShort":1747,"idAttachmentCover":"5af6e0740be4f8e8fb55f783","labels":[{"id":"54d490bf74d650d56719d346","idBoard":"4f2ef2f82e7ecf843fb79649","name":"Auftrag-angefragt","color":"orange"},{"id":"58b6b01cced82109ff8568e0","idBoard":"4f2ef2f82e7ecf843fb79649","name":"2018","color":null}],"idLabels":["54d490bf74d650d56719d346","58b6b01cced82109ff8568e0"],"manualCoverAttachment":false,"name":"* bei Angebot / 1. Erstellung Angebot","pos":224256,"shortLink":"9HqdsTdm","shortUrl":"https://trello.com/c/9HqdsTdm","subscribed":false,"url":"https://trello.com/c/9HqdsTdm/1747-bei-angebot-1-erstellung-angebot","limits":{}}
Received: {"id":"5af6e0740be4f8e8fb55f782","badges":{"votes":0,"attachmentsByType":{"trello":{"board":0,"card":0}},"viewingMemberVoted":false,"subscribed":false,"fogbugz":"","checkItems":21,"checkItemsChecked":0,"comments":0,"attachments":1,"description":true,"due":null,"dueComplete":false},"attachments":[{"id":"5af6e0740be4f8e8fb55f783","bytes":9782,"date":"2017-04-17T11:00:27.936Z","edgeColor":"#fbfbfb","idMember":"5af6e0740be4f8e8fb55f784","isUpload":true,"mimeType":null,"name":"am 17.4.2017 um 13:00:29 hochladen.png","previews":[{"bytes":1512,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/70x50/b517781044d2e4a2cea9e665ddd4a013/am_17.4.2017_um_13_00_29_hochladen.png","height":50,"width":70,"_id":"5af6e0740be4f8e8fb55f785","scaled":false},{"bytes":11454,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/250x150/9a4b3e2477e69a64541fd20db82ce567/am_17.4.2017_um_13_00_29_hochladen.png","height":150,"width":250,"_id":"5af6e0740be4f8e8fb55f786","scaled":false},{"bytes":5164,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/150x18/c2f87a31cc4f516e23d877ca13a180bc/am_17.4.2017_um_13_00_29_hochladen.png","height":18,"width":150,"_id":"5af6e0740be4f8e8fb55f787","scaled":true},{"bytes":14339,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/300x37/7f725ab87b73992151475e1ec9030010/am_17.4.2017_um_13_00_29_hochladen.png","height":37,"width":300,"_id":"5af6e0740be4f8e8fb55f788","scaled":true},{"bytes":9782,"height":41,"width":335,"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/335x41/931fb24b7bb10ee1fab78f577b29adc4/am_17.4.2017_um_13_00_29_hochladen.png","_id":"5af6e0740be4f8e8fb55f789","scaled":true}],"url":"https://trello-attachments.s3.amazonaws.com/4f2ef2f82e7ecf843fb79649/5af6e0740be4f8e8fb55f782/x/2fab975fd20ddd390557db42fcf032d4/am_17.4.2017_um_13_00_29_hochladen.png","pos":16384}],"checkItemStates":[],"closed":false,"dueComplete":false,"dateLastActivity":"2018-05-12T12:39:16.903Z","desc":"The description","descData":{"emoji":{}},"due":null,"email":null,"idBoard":"4f2ef2f82e7ecf843fb79649","idChecklists":["5af6e0740be4f8e8fb55f78d","5af6e0740be4f8e8fb55f7a0"],"stickers":[],"idList":"52ce972a1c855c5a309edd82","idMembers":[],"idMembersVoted":[],"idShort":1747,"idAttachmentCover":"5af6e0740be4f8e8fb55f783","labels":[{"id":"54d490bf74d650d56719d346","idBoard":"4f2ef2f82e7ecf843fb79649","name":"Auftrag-angefragt","color":"orange"},{"id":"58b6b01cced82109ff8568e0","idBoard":"4f2ef2f82e7ecf843fb79649","name":"2018","color":null}],"idLabels":["54d490bf74d650d56719d346","58b6b01cced82109ff8568e0"],"manualCoverAttachment":false,"name":"* bei Angebot / 1. Erstellung Angebot","pos":224256,"shortLink":"9HqdsTdm","shortUrl":"https://trello.com/c/9HqdsTdm","subscribed":false,"url":"https://trello.com/c/9HqdsTdm/1747-bei-angebot-1-erstellung-angebot","limits":{}}
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Manatee.Trello.Internal.Caching.ConcurrentCache.Find[T](String id)
   at Manatee.Trello.Internal.Caching.CachingObjectFactory.GetFromCache[T](IJsonCacheable json, TrelloAuthorization auth)
...
```

Pretty-printed JSON
```json
{
  "id": "5af6e0740be4f8e8fb55f782",
  "badges": {
    "votes": 0,
    "attachmentsByType": {
      "trello": {
        "board": 0,
        "card": 0
      }
    },
    "viewingMemberVoted": false,
    "subscribed": false,
    "fogbugz": "",
    "checkItems": 21,
    "checkItemsChecked": 0,
    "comments": 0,
    "attachments": 1,
    "description": true,
    "due": null,
    "dueComplete": false
  },
  "attachments": [
    {
      "id": "5af6e0740be4f8e8fb55f783",
      "bytes": 9782,
      "date": "2017-04-17T11:00:27.936Z",
      "edgeColor": "#fbfbfb",
      "idMember": "5af6e0740be4f8e8fb55f784",
      "isUpload": true,
      "mimeType": null,
      "name": "am 17.4.2017 um 13:00:29 hochladen.png",
      "previews": [
        {
          "bytes": 1512,
          "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/70x50\/b517781044d2e4a2cea9e665ddd4a013\/am_17.4.2017_um_13_00_29_hochladen.png",
          "height": 50,
          "width": 70,
          "_id": "5af6e0740be4f8e8fb55f785",
          "scaled": false
        },
        {
          "bytes": 11454,
          "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/250x150\/9a4b3e2477e69a64541fd20db82ce567\/am_17.4.2017_um_13_00_29_hochladen.png",
          "height": 150,
          "width": 250,
          "_id": "5af6e0740be4f8e8fb55f786",
          "scaled": false
        },
        {
          "bytes": 5164,
          "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/150x18\/c2f87a31cc4f516e23d877ca13a180bc\/am_17.4.2017_um_13_00_29_hochladen.png",
          "height": 18,
          "width": 150,
          "_id": "5af6e0740be4f8e8fb55f787",
          "scaled": true
        },
        {
          "bytes": 14339,
          "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/300x37\/7f725ab87b73992151475e1ec9030010\/am_17.4.2017_um_13_00_29_hochladen.png",
          "height": 37,
          "width": 300,
          "_id": "5af6e0740be4f8e8fb55f788",
          "scaled": true
        },
        {
          "bytes": 9782,
          "height": 41,
          "width": 335,
          "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/335x41\/931fb24b7bb10ee1fab78f577b29adc4\/am_17.4.2017_um_13_00_29_hochladen.png",
          "_id": "5af6e0740be4f8e8fb55f789",
          "scaled": true
        }
      ],
      "url": "https:\/\/trello-attachments.s3.amazonaws.com\/4f2ef2f82e7ecf843fb79649\/5af6e0740be4f8e8fb55f782\/x\/2fab975fd20ddd390557db42fcf032d4\/am_17.4.2017_um_13_00_29_hochladen.png",
      "pos": 16384
    }
  ],
  "checkItemStates": [
    
  ],
  "closed": false,
  "dueComplete": false,
  "dateLastActivity": "2018-05-12T12:39:16.903Z",
  "desc": "The description",
  "descData": {
    "emoji": {
      
    }
  },
  "due": null,
  "email": null,
  "idBoard": "4f2ef2f82e7ecf843fb79649",
  "idChecklists": [
    "5af6e0740be4f8e8fb55f78d",
    "5af6e0740be4f8e8fb55f7a0"
  ],
  "stickers": [
    
  ],
  "idList": "52ce972a1c855c5a309edd82",
  "idMembers": [
    
  ],
  "idMembersVoted": [
    
  ],
  "idShort": 1747,
  "idAttachmentCover": "5af6e0740be4f8e8fb55f783",
  "labels": [
    {
      "id": "54d490bf74d650d56719d346",
      "idBoard": "4f2ef2f82e7ecf843fb79649",
      "name": "Auftrag-angefragt",
      "color": "orange"
    },
    {
      "id": "58b6b01cced82109ff8568e0",
      "idBoard": "4f2ef2f82e7ecf843fb79649",
      "name": "2018",
      "color": null
    }
  ],
  "idLabels": [
    "54d490bf74d650d56719d346",
    "58b6b01cced82109ff8568e0"
  ],
  "manualCoverAttachment": false,
  "name": "* bei Angebot \/ 1. Erstellung Angebot",
  "pos": 224256,
  "shortLink": "9HqdsTdm",
  "shortUrl": "https:\/\/trello.com\/c\/9HqdsTdm",
  "subscribed": false,
  "url": "https:\/\/trello.com\/c\/9HqdsTdm\/1747-bei-angebot-1-erstellung-angebot",
  "limits": {
    
  }
}
```

**Comment by agross** [comment]
It seems to be related to the board or template card. With one board I can create a copy without errors, but it fails on the production board.

**Comment by agross** [comment]
To be more precise: It depends on the template card.

**Comment by agross** [comment]
I could further track this down to template cards containing image attachments (PNG or JPEG).

**Comment by gregsdennis** [comment]
The attachment did it.  I've updated the client test.  I'll try to work on the fix tonight.

**Comment by agross** [comment]
No hurry, I'm on vacation next week. Good luck fixing the bug!

**Comment by gregsdennis** [comment]
Arggh!!! The attachment preview ID field is named `_id`, not `id` like the rest of everything in this God-forsaken API!!!

**Comment by agross** [comment]
It's the small inconsistencies that make you love an API ;-)

**Comment by gregsdennis** [comment]
Okay. v3.0.10 should be available soon.  Good luck.

**Comment by agross** [comment]
Thanks, it seems to be working now!
