### ISSUE TITLE
Method 'get_CustomField' does not have an implementation

### ISSUE THREAD

**Issue by BruceP99166** [gregsdennis/Manatee.Trello#217]
**Describe the bug**
Using Manatee.Trello libraries to access Trello data from a c# program.  Just upgraded to latest stable versions.  Now the program fails.  Thanks for any help you can give.

Here are the error details
System.TypeLoadException
  HResult=0x80131522
  Message=Method 'get_CustomField' in type 'Manatee.Trello.ManateeJson.Entities.ManateeActionData' from assembly 'Manatee.Trello.ManateeJson, Version=2.0.0.0, Culture=neutral, PublicKeyToken=fbb8336f4f768592' does not have an implementation.
  Source=Manatee.Trello.ManateeJson
  StackTrace:
   at Manatee.Trello.ManateeJson.ManateeSerializer.InitializeAbstractionMap(JsonSerializer serializer)
   at Manatee.Trello.ManateeJson.ManateeSerializer..ctor()
   at Project1.Form1.button2_Click(Object sender, EventArgs e) in C:\Users\Bruce Pike Rice\Documents\Source\Project1\Project1\Form1.cs:line 34
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Project1.Program.Main() in C:\Users\Bruce Pike Rice\Documents\Source\Project1\Project1\Program.cs:line 19

Here is a small winforms app to show the problem:
using System;
using System.Windows.Forms;

using Manatee.Trello;
using Manatee.Trello.ManateeJson;

namespace Project1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void button2_Click(object sender, EventArgs e)
        {
            // Manatee configuration
            var serializer = new ManateeSerializer();
            TrelloConfiguration.Serializer = serializer;
            TrelloConfiguration.Deserializer = serializer;
            TrelloAuthorization.Default.AppKey = "MyAppKey";
            TrelloAuthorization.Default.UserToken = "MyUserToken";

            string BrdId = "5ab159c6e49acdc7d971134d";
            var Brd = new Board(BrdId);
            string BrdNm = Brd.Name;

        }
    }
}

**To Reproduce**
Please add test code or steps to reproduce the behavior:
1. Open In Visual Studio 
2. Replace MyAppKey and MyUserToken with valid values.
3. start program as debug.  Click on button.
4. See error at line 24

**Expected behavior**
Program to complete with no error.

**Screenshots**
![capture](https://user-images.githubusercontent.com/17090922/40089025-572e3700-586f-11e8-960c-fd6cade8981e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
- .Net Target (Fwk 4.6.1) 
- .Net Fwk Version 4.7.03056

**Manatee packages installed**

- Manatee.Json v9.9.0
- Manatee.Trello v3.0.10
- Manatee.Trello.ManateeJson v2.3.0
- Manatee.Trello.WebApi v2.0.3

**Comment by gregsdennis** [comment]
@BruceP99166 what version of Manatee.Trello are you using?  If you're using version 3+, then you [don't need to do the JSON serializer setup](https://github.com/gregsdennis/Manatee.Trello/blob/master/docs/1.%20Getting%20started.md#configuration).

**Comment by BruceP99166** [comment]
Just added the Manatee versions.
