### ISSUE TITLE
TrelloAuthorization Exception

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#23]
Dave Thomas (DaveTheThomas on BitBucket) wrote:

>First of all thank you for your body of work and your willingness to support the community. I am new here so I will include some detail info without swamping this thread.

>The basic issue is a TrelloAuthorization Exception after specifying TrelloAuthorization.Default.AppKey = "&lt;mykey>";

>Any help is appreciated

>##Dave

>Trello user:davethomas42

>Nuget package versions for: Manatee.Trello (Manatee.Trello" version="1.8.2" targetFramework="net45") Manatee.Trello.ManateeJson (Manatee.Trello.ManateeJson" version="1.4.0" targetFramework="net45" ) Manatee.Json (Manatee.Json" version="3.2.1" targetFramework="net45" ) Manatee.Trello.RestSharp (Manatee.Trello.RestSharp" version="1.2.0.2" targetFramework="net45") RestSharp (Manatee.Trello.RestSharp" version="1.2.0.2" targetFramework="net45") Manatee.Trello.WebApi (Manatee.Trello.WebApi" version="1.0.1" targetFramework="net45" ) .Net framework version (Targets .NET framework 4.5)

>Issue: Manatee.Trello.Exceptions.TrelloInteractionException' occurred in Manatee.Trello.dll Source:Manatee.Trello Message:Trello has reported an error with the request.

>Occurs: @ TrelloAuthorization.Default.AppKey = "<mykey>";

>Detail: InnerException Message: One or more errors occurred. Inner Exception Stack snippet

>at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow) in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\ExceptionHandling\DebugLog.cs:line 49 at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request) in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 85 at Manatee.Trello.Internal.DataAccess.JsonRepository.ExecuteT in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 51 at Manatee.Trello.Me.GetId() in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Me.cs:line 115 at Manatee.Trello.Me..ctor() in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Me.cs:line 104 at Manatee.Trello.Member.get_Me() in C:\Users\Greg\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Member.cs:line 61

>InnerException.InnerException Message {"Cannot determine type. Path: '$'"}

>InnerException.InnerException Stack Trace

>---

>at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Manatee.Trello.WebApi.WebApiFormatter.Deserialize(Type type, String content) in C:\Users\dthomas\Downloads\MANATEE API\gregsdennis-manatee.trello-31428d66c650\Manatee.Trello.WebApi\WebApiFormatter.cs:line 72 at Manatee.Trello.WebApi.WebApiFormatter.Read(Type type, Stream readStream) in C:\Users\dthomas\Downloads\MANATEE API\gregsdennis-manatee.trello-31428d66c650\Manatee.Trello.WebApi\WebApiFormatter.cs:line 59 at Manatee.Trello.WebApi.WebApiFormatter.<>cDisplayClass5_0.<ReadFromStreamAsync>b0() in C:\Users\dthomas\Downloads\MANATEE API\gregsdennis-manatee.trello-31428d66c650\Manatee.Trello.WebApi\WebApiFormatter.cs:line 44

**Comment by gregsdennis** [comment]
Dave Thomas, Thanks for using Manatee.Trello. There are a few things that can be the issue here.

First, you only need one REST provider, either Manatee.Trello.RestSharp or Manatee.Trello.WebApi, but not both. From the stack trace, it looks like you're using the WebApi version. You can get rid of the RestSharp one.

Second, Trello's responding with the error in plain text. The WebApi isn't set up to handle that yet. (I have another issue (#22) that I'll publish soon that will expose the exact error that Trello's returning to make these issues easier to debug.) For now you can capture the problem with a network traffic monitor like Fiddler.

It's likely that the problem is that you don't have a valid token. Please read the "More on Authorization" section on the [Usage wiki page](/gregsdennis/Manatee.Trello/wiki/Usage).

Let me know if that helps.

**Comment by gregsdennis** [comment]
Dave Thomas I've published that update that'll allow you to see the errors that Trello returns. Please update and send me the logging output.

**Comment by gregsdennis** [comment]
Dave Thomas (DaveTheThomas on BitBucket) wrote:

>Greg, I would like to remove this from the bugs list. I tried the auth method described in the (more) section but after all (and fitzing with various tokens) this worked

>            TrelloAuthorization.Default.AppKey = "<mykey>;
             try
             {
                TrelloAuthorization.Default.UserToken = "<mytoken>";
             }
              catch { //do some notification
                          return; }

>I also went into trello and deleted all applications from the list and went to (https://trello.com/1/authorize?key=<mykey>&name=My+Application&expiration=1day&response_type=token&scope=read,write)

>Just getting all the noobishness out of the way. Just sayin'

>btw I did update the Nuget package for WebApi

>Please remove "bug" or mark appropriately

**Comment by gregsdennis** [comment]
Dave Thomas (DaveTheThomas on BitBucket) wrote:

>Now all I have to do is learn how to enumerate comments ... searching docs ;)

**Comment by gregsdennis** [comment]
There shouldn't be any exceptions thrown from assigning those `TrelloAuthorization` properties. Those are just regular properties. There's no logic behind them.

It will, however, throw an exception when you try to make a call.
