### ISSUE TITLE
NRE in NotificationContext

### ISSUE THREAD

**Issue by gregsdennis** [gregsdennis/Manatee.Trello#30]
NotificationContext, line 42 needs a `?.`.

Check other context objects for the same issue.

**Comment by gregsdennis** [comment]
Nathan S Here you go.

**Comment by gregsdennis** [comment]
Nathan S (nsta on BitBucket) wrote:

>Oops, I guess you wanted a separate issue raised eh? Sorry >_<

**Comment by gregsdennis** [comment]
Nathan S (nsta on BitBucket) wrote:

>For reference:

>     System.NullReferenceException: Object reference not set to an instance of an object.
    at Manatee.Trello.Internal.Synchronization.NotificationContext.<>c.<.cctor>b__3_1(IJsonNotification d, Member o) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\Synchronization\NotificationContext.cs:line 42
    at Manatee.Trello.Internal.Synchronization.Property`2.<>c__DisplayClass0_0.<.ctor>b__1(TJson j, Object o) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\Synchronization\Property.cs:line 44
    at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge(TJson json) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\Synchronization\SynchronizationContext.cs:line 225
    at Manatee.Trello.Notification..ctor(IJsonNotification json, TrelloAuthorization auth) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Notification.cs:line 161
    at Manatee.Trello.Internal.Caching.CachingObjectFactory.<>c.<.cctor>b__2_10(IJsonCacheable j, TrelloAuthorization a) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\Caching\CachingObjectFactory.cs:line 66
    at Manatee.Trello.Internal.Caching.CachingObjectFactory.GetFromCache[T](IJsonCacheable json, TrelloAuthorization auth) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\Caching\CachingObjectFactory.cs:line 78
    at Manatee.Trello.ReadOnlyNotificationCollection.<Update>b__3_0(IJsonNotification jn) in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\NotificationCollection.cs:line 62
    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
    at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
    at Manatee.Trello.ReadOnlyNotificationCollection.Update() in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\NotificationCollection.cs:line 60
    at Manatee.Trello.ReadOnlyCollection`1.GetEnumerator() in C:\Users\gdennis\OneDrive\Projects\Manatee.Trello\Manatee.Trello\ReadOnlyCollection.cs:line 79
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    at TrelloDMTCmd.Program.Main(String[] args) in c:\Users\lmi032\Documents\Visual Studio 2013\Projects\TrelloDMT\TrelloDMTCmd\Program.cs:line 30

**Comment by gregsdennis** [comment]
Nathan S, please see Manatee.Trello v1.9.1.
