### ISSUE TITLE
Error When Running via Reflection

### ISSUE THREAD

**Issue by damienturnbull** [gregsdennis/Manatee.Trello#305]
**Describe the bug**
We've written a function that returns 'Task' in .Net 4.6.2. This function then integrates with Trello via the Manatee classes.

eg await board.Lists.Refresh();

When we call this function via Reflection, we get an error upon calling 'await board.Lists.Refresh();

If we don't call it via Reflection, it works fine. We can't work out why the Reflection call would be any different to calling the function directly.

System.TypeInitializationException: The type initializer for 'Manatee.Json.Serialization.SerializerFactory' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Manatee.Json.Serialization.SerializerFactory..cctor()
   --- End of inner exception stack trace ---
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestResponse response)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<ProcessRequest>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<Execute>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.ReadOnlyListCollection.<PerformRefresh>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by gregsdennis** [comment]
Thanks for reporting this, but why are you trying to call this via reflection?

> Retrieve the LoaderExceptions property for more information.

Could you do this, please?  Also, can you create a snippet that replicates the problem?

**Comment by gregsdennis** [comment]
Closing as it's been 2 weeks with no response.
