### ISSUE TITLE
board.Refresh() generate an TypeInitializationException for 'Manatee.Trello.Json.DefaultJsonSerializer'

### ISSUE THREAD

**Issue by arobasse2** [gregsdennis/Manatee.Trello#322]
Hello

I restarted my application since 2020, and I have now an error when executing this code:
```
_factory = new TrelloFactory();
_board = _factory.Board(TodoBoardId);
AsyncHelper.RunSync(() => _board.Refresh());
```

I get the following exception at : `_board.Refresh()`
```
System.TypeInitializationException : Une exception a été levée par l'initialiseur de type pour 'Manatee.Trello.Json.DefaultJsonSerializer'.
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestResponse response)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<ProcessRequest>d__7`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<Execute>d__1`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.<GetData>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.DeletableSynchronizationContext`1.<GetData>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.<GetBasicData>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext.<Synchronize>d__22.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TimeTracking.AsyncHelper.RunSync(Func`1 func) in C:\Users\EFD3\source\repos\TimeTracking\TimeTracking\AsyncHelper.cs:line 25
   at TimeTracking.Trello.TrelloService..ctor() in C:\Users\EFD3\source\repos\TimeTracking\TimeTracking\Trello\TrelloService.cs:line 47
   at TimeTracking.Main.<InitializeServices>b__5_0() in C:\Users\EFD3\source\repos\TimeTracking\TimeTracking\Main.cs:line 65
   at TimeTracking.Main.loadingBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\EFD3\source\repos\TimeTracking\TimeTracking\Main.cs:line 152

```

I have the following NuGet packages installed
Manatee.Trello	: 4.1.1
Manatee.Json	: 12.0.2

I don't know if it is a change at Trello level.
My app was working well in 2019, end of December.
I don't know if there is a link...

I can provide you an extract of my application if you want.

Best regards

**Comment by gregsdennis** [comment]
Thanks for reporting.

Two additional things would help greatly:

- any inner exceptions
- the data that Trello is returning

If you like you can DM me on Slack or email me.

**Comment by gregsdennis** [comment]
All of my tests are passing, so it's not a global issue.  Please let me know what additional details you can find.

**Comment by gregsdennis** [comment]
Did you recently update Manatee.Json?

**Comment by gregsdennis** [comment]
Yeah, that's it. I haven't updated Manatee.Trello to use v12 of Manatee.Json yet.  You'll need to downgrade to v11.

**Comment by arobasse2** [comment]
Hello and sorry for late response, time zone difference.

Thank a lot for your investigation, it successfully solve my problem.
I forgotten I had made an upgrade of Manatee.Json...

Thank again for your work on those libs
Have a nice new year.
Bye

**Comment by gregsdennis** [comment]
I've updated to Manatee.Json 12. Please see v3.2.1.
