### ISSUE TITLE
Just trying to get started: TargetInvocationException

### ISSUE THREAD

**Issue by derekantrican** [gregsdennis/Manatee.Trello#327]
I'm new to Manatee.Trello and just trying to get started. Here's what I've got (.NET Framework console app):

```
    class Program
    {
        static TrelloFactory factory;
        static void Main(string[] args)
        {
            Auth();
            GetBoards().Wait();
        }

        public static void Auth()
        {
            TrelloAuthorization.Default.AppKey = "APPKEY";
            TrelloAuthorization.Default.UserToken = "TOKEN";

            factory = new TrelloFactory();
        }

        public static async Task<List<Board>> GetBoards()
        {
            List<Board> result = new List<Board>();

            try
            {
                IMe me = await factory.Me();
                foreach (Board board in me.Boards)
                    result.Add(board);
            }
            catch (Exception ex)
            {

            }

            return result;
        }
    }
```

Whenever I run it, the `factory.Me()` line throws `Exception has been thrown by target of an invocation`. Am I doing something obviously wrong? I couldn't seem to find docs that contain, step-by-step, how to get started.

**Comment by gregsdennis** [comment]
Yeah, getting this a lot. I'm trying to update, but the build is stupid.  See #322.

**Comment by derekantrican** [comment]
Ok, good to know. Should I wait for a new version to come out or revert back to a previous one?

**Comment by gregsdennis** [comment]
I suggest going back for now since it won't work with the new one.

**Comment by derekantrican** [comment]
Ok, any suggested versions? I've reverted to Manatee.Trello v4.0.0 and Manatee.Json v11.0.0 and still getting the same error

**Comment by gregsdennis** [comment]
Use the latest Manatee.Trello with the latest 11.x.y of Manatee.Json.

**Comment by derekantrican** [comment]
Ok, I've got Manatee.Trello 4.1.1 and Manatee.Json 11.0.4. Still seeing the exception. Here's the stack trace if that's helpful:

```
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestResponse response)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<ProcessRequest>d__7`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.<Execute>d__1`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.<GetData>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.<GetBasicData>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext.<Synchronize>d__22.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manatee.Trello.TrelloFactory.<Me>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ManateeTest.Program.<GetBoards>d__3.MoveNext() in C:\Users\deantric\source\repos\ManateeTest\ManateeTest\Program.cs:line 34
```

**Comment by gregsdennis** [comment]
is there an inner exception?

**Comment by derekantrican** [comment]
If I follow the inner exceptions down I get this:

`Requested value 'reopenBoard' was not found.`
```
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Manatee.Json.Serialization.Internal.Serializers.EnumNameSerializer.Deserialize(SerializationContext context)
   at Manatee.Json.Serialization.Internal.Serializers.DefaultValueSerializer.Deserialize(SerializationContext context)
   at Manatee.Json.Serialization.Internal.Serializers.SchemaValidator.Deserialize(SerializationContext context)
   at Manatee.Json.Serialization.JsonSerializer.Deserialize(SerializationContext context)
   at Manatee.Json.Serialization.Internal.Serializers.NullableSerializer._Decode[T](SerializationContext context)
```

**Comment by gregsdennis** [comment]
Ah!  That's a different error!  You found a new action type.  I'll have to add that.

**Comment by gregsdennis** [comment]
Okay... I've added the new action type and updated to Manatee.Json 12.  Please see v3.2.1.

**Comment by derekantrican** [comment]
Excellent! I will check it out when I next get a chance

**Comment by derekantrican** [comment]
I'm still seeing the issue. But I downloaded the source of Manatee.Trello and figured it out: the value `reopenBoard` is actually missing from `NotificationType.cs`, not `ActionType.cs` (though it may also be handy to have it there).

I would make the change myself but I am not quite familiar with the `1 << 7` notation.

**Comment by gregsdennis** [comment]
[*deep inhale, followed by prolonged exhale*]

I actually wondered about that as I was committing it...

**Comment by gregsdennis** [comment]
okay... try 4.2.2.
