### ISSUE TITLE
get_StatusCode not implemented in WebApiRestResponse

### ISSUE THREAD

**Issue by martindafonte** [gregsdennis/Manatee.Trello#75]
Doing any operation results in the following exception:

> Method 'get_StatusCode' in type 'Manatee.Trello.WebApi.WebApiRestResponse' from assembly 'Manatee.Trello.WebApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f7ae00e0424b8d0e' does not have an implementation.":"Manatee.Trello.WebApi.WebApiRestResponse"

StackTrace
```
   at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow) in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\ExceptionHandling\DebugLog.cs:line 26
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request) in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 62
   at Manatee.Trello.Internal.DataAccess.JsonRepository.Execute[T](TrelloAuthorization auth, Endpoint endpoint, IDictionary`2 parameters) in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Internal\DataAccess\JsonRepository.cs:line 28
   at Manatee.Trello.Me.GetId() in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Me.cs:line 93
   at Manatee.Trello.Me..ctor() in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Me.cs:line 82
   at Manatee.Trello.Member.get_Me() in C:\Users\gregd\OneDrive\Projects\Manatee.Trello\Manatee.Trello\Member.cs:line 37

```   

```
<packages>
  <package id="Manatee.Json" version="5.2.1" targetFramework="net461" />
  <package id="Manatee.StateMachine" version="1.1.2" targetFramework="net45" />
  <package id="Manatee.Trello" version="1.17.0" targetFramework="net461" />
  <package id="Manatee.Trello.CustomFields" version="1.0.0" targetFramework="net461" />
  <package id="Manatee.Trello.ManateeJson" version="1.7.1" targetFramework="net461" />
  <package id="Manatee.Trello.RestSharp" version="1.3.0" targetFramework="net461" />
  <package id="Manatee.Trello.WebApi" version="1.1.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net461" />
  <package id="Minimod.PrettyDateAndTime" version="1.1.0" targetFramework="net45" />
  <package id="Minimod.PrettyPrint" version="1.1.0" targetFramework="net45" />
  <package id="Minimod.PrettyText" version="2.0.1" targetFramework="net45" />
  <package id="Minimod.PrettyTypeSignatures" version="1.1.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="net461" />
  <package id="RestSharp" version="105.2.3" targetFramework="net45" requireReinstallation="true" />
  <package id="RestSharpSigned" version="105.2.3" targetFramework="net45" requireReinstallation="true" />
</packages>
```

```
            TrelloConfiguration.Serializer = serializer;
            TrelloConfiguration.Deserializer = serializer;
            TrelloConfiguration.JsonFactory = new ManateeFactory();
            TrelloConfiguration.RestClientProvider = new Manatee.Trello.WebApi.WebApiClientProvider();
            TrelloConfiguration.ExpiryTime = new System.TimeSpan(0, 0, 120);
            TrelloAuthorization.Default.AppKey = pKey ?? key;
            TrelloAuthorization.Default.UserToken = pToken ?? token;
            TrelloProcessor.ConcurrentCallCount = 3;
```

**Comment by gregsdennis** [comment]
I ran it in my test suite and it seems to work, so I downloaded the Nuget package.  When I open the DLL with a decompiler, I see this as the definition of WebApiRestResponse:

    internal class WebApiRestResponse : IRestResponse
    {
        public string Content { get; set; }
        public Exception Exception { get; set; }
    }

Sure enough... it's missing... something.  I don't know how this happened, but I'll rebuild and republish the WebApi package.  (I'll check the DLL first 😄)

**Comment by gregsdennis** [comment]
Please see v1.1.0.1 for the fix.
