### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by ardentra** [gregsdennis/Manatee.Trello#92]
This just started today on one of our boards and can't seem to figure out why. This same code works fine on other boards but I am getting some weirdness here:

System.Reflection.TargetInvocationException occurred
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=Manatee.Trello
  StackTrace:
   at Manatee.Trello.Internal.ExceptionHandling.DebugLog.Error(Exception e, Boolean shouldThrow)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.ValidateResponse(IRestRequest request)
   at Manatee.Trello.Internal.DataAccess.JsonRepository.Execute[T](TrelloAuthorization auth, Endpoint endpoint, IDictionary`2 parameters)
   at Manatee.Trello.Internal.Synchronization.SearchContext.GetData()
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext`1.Merge()
   at Manatee.Trello.Internal.Synchronization.SynchronizationContext.Synchronize(Boolean force)
   at Manatee.Trello.Search.get_Cards()
   at TrelloAutomation.Program.GetCards(String boardString, String labelString, String listString, String outputFile, Boolean writeFile, Boolean moveCards, Boolean labelCards, Int32 SearchMode) in C:\Repositories\chromatics\Applications\Trello\TrelloAutomation\TrelloAutomation\Program.cs:line 250
   at TrelloAutomation.Program.Main(String[] args) in C:\Repositories\chromatics\Applications\Trello\TrelloAutomation\TrelloAutomation\Program.cs:line 179

Inner Exception 1:
ArgumentOutOfRangeException: A valid UTF32 value is between 0x000000 and 0x10ffff, inclusive, and should not include surrogate codepoint values (0x00d800 ~ 0x00dfff).

![image](https://user-images.githubusercontent.com/12415527/27699033-8f93804e-5cbe-11e7-81e8-cbd438b13e29.png)

**Comment by ardentra** [comment]
So it turns out after I moved some cards individually this automagically started working again. I'll see if I can isolate the card that was causing this issue.

**Comment by gregsdennis** [comment]
Thanks for the report.  Please let me know what you find.

**Comment by gregsdennis** [comment]
From that inner exception it looks like one of your cards may have a weird character in the title or description.

**Comment by gregsdennis** [comment]
@ardentra were you able to resolve this?
